name: Deploy

# https://github.com/marketplace/actions/deploy-to-github-pages

on:
  workflow_run:
    workflows: ['CI']
    branches: 'master'
    types:
      - completed

jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.1
        with:
          persist-credentials: false

      - uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: build
          CLEAN: true
