name: CI

on:
  push:
    branches:
      - '**'
      - '!main'

jobs:
  test_and_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.1
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: npm ci --no-optional
      - run: npm test

      - name: 'Build web app artifacts'
        run: npm run build

      - name: 'Build native app artifacts'
        env:
          GH_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: npm run build:native:linux
      - uses: actions/upload-artifact@v3
        with:
          name: build-output
          path: |
            build
            !build/native/linux-unpacked/

      - name: Prepare Web Artifacts
        run: |
          zip farmhand-web -r build/* -x build/native/**\* -x build/native/
      - name: Prepare Native Artifacts
        run: |
          zip farmhand-native -r build/native/ -x build/native/linux-unpacked/**\* -x build/native/linux-unpacked/

      - name: Create Release
        id: create-release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: true
          prerelease: true

      - name: Upload Release Web Asset
        id: upload-release-web-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the Create Release step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps
          asset_path: ./farmhand-web.zip
          asset_name: farmhand-web.zip
          asset_content_type: application/zip

      - name: Upload Release Native Asset
        id: upload-release-native-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./farmhand-native.zip
          asset_name: farmhand-native.zip
          asset_content_type: application/zip
