name: CI

on:
  push:
    branches:
      - '**'
      - '!main'

jobs:
  test_and_build:
    runs-on: ubuntu-latest
    steps:
      - env:
        # Needed for electron-builder
        GH_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      - uses: actions/checkout@v2.3.1
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: npm ci --no-optional
      - run: npm test
      - run: npm run build
      - run: npm run build:native:linux
      - uses: actions/upload-artifact@v3
        with:
          name: build-output
          path: build
