name: Post deployment notification to Discord

# https://github.com/marketplace/actions/actions-for-discord
# https://docs.github.com/en/developers/webhooks-and-events/webhook-events-and-payloads#push

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Discord notification
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        uses: Ilshidur/action-discord@0.3.0
        with:
          args: 'A game update is shipping to https://jeremyckahn.github.io/farmhand/ now! Take a look at what changed: {{ EVENT_PAYLOAD.compare }}'
