name: CI

on:
  release:
    types: [created]

jobs:
  test_and_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.1
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: npm ci --no-optional
      - name: 'Build Linux artifacts'
        env:
          GH_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: npm run build:native:linux
      - uses: actions/upload-artifact@v3
        with:
          name: build-output
          path: |
            build
            !build/native/linux-unpacked/
