name: Publish NPM Package

on:
  push:
    branches:
      - '!*'
    tags:
      - 'v*'

jobs:
  publish_package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.1
      - uses: actions/setup-node@v1
        with:
          node-version: 14
          registry-url: 'https://registry.npmjs.org'
      - run: npm ci
      - run: npm test
      - run: PUBLIC_URL='./' npm run build
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish to itch.io
        uses: josephbmanley/butler-publish-itchio-action@master
        env:
          BUTLER_CREDENTIALS: ${{ secrets.ITCH_TOKEN }}
          CHANNEL: html5
          ITCH_GAME: Farmhand
          ITCH_USER: jeremyckahn
          PACKAGE: build
