# https://github.blog/changelog/2020-07-06-github-actions-manual-triggers-with-workflow_dispatch/
on:
  workflow_dispatch:
    inputs:
      releaseType:
        description: 'Release type'
        required: true
        default: 'patch'

jobs:
  triggerRelease:
    runs-on: ubuntu-latest
    steps:
      - name: Check out master
        uses: actions/checkout@v2.3.1
        with:
          ref: master
          fetch-depth: 0

      - name: Check out develop
        uses: actions/checkout@v2.3.1
        with:
          ref: develop
          fetch-depth: 0

      - name: Setup Git user
        uses: fregante/setup-git-user@v1

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Install dependencies
        run: npm ci

      - name: Tag release
        run: npm version ${{ github.event.inputs.releaseType }}

      - name: Push tag commit back to develop
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          tags: true

      - name: Sync branches
        run: git checkout master && git merge develop && git checkout develop

      - name: Switch back to master
        run: git checkout master

      # Push merge commit back to master and trigger downstream workflows
      # https://github.community/t/push-from-action-does-not-trigger-subsequent-action/16854/2
      - name: Trigger deployment
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
